#!/usr/bin/env bash
#
# Cloud Agent install script for NetBox.
#
# Idempotent repository bootstrap: installs system packages, prepares
# PostgreSQL and Redis, creates the Python virtualenv, installs Python
# dependencies, generates a local configuration.py (gitignored), builds
# the local docs, collects static files, applies migrations, and ensures
# a development superuser exists.
#
# This script is safe to run repeatedly.
set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
VENV_DIR="${HOME}/.venv/netbox"
PG_VERSION=16
PG_CLUSTER=main

DB_NAME=netbox
DB_USER=netbox
DB_PASSWORD=netbox

DJANGO_SUPERUSER_USERNAME=admin
DJANGO_SUPERUSER_PASSWORD=admin1234
DJANGO_SUPERUSER_EMAIL=admin@example.com

echo "==> [1/9] Installing system packages"
export DEBIAN_FRONTEND=noninteractive
sudo apt-get update -qq
sudo apt-get install -y -qq \
    python3 python3-pip python3-venv python3-dev \
    build-essential libxml2-dev libxslt1-dev libffi-dev libpq-dev \
    libssl-dev zlib1g-dev git postgresql postgresql-contrib redis-server

echo "==> [2/9] Starting PostgreSQL (needed for migrations)"
sudo pg_ctlcluster "${PG_VERSION}" "${PG_CLUSTER}" start 2>/dev/null || true
for _ in $(seq 1 30); do
    if sudo pg_isready -q; then break; fi
    sleep 1
done

echo "==> [3/9] Starting Redis"
sudo redis-server /etc/redis/redis.conf --daemonize yes 2>/dev/null || true
for _ in $(seq 1 30); do
    if redis-cli ping >/dev/null 2>&1; then break; fi
    sleep 1
done

echo "==> [4/9] Ensuring database role and database exist"
if ! sudo -u postgres psql -tAc "SELECT 1 FROM pg_roles WHERE rolname='${DB_USER}'" | grep -q 1; then
    sudo -u postgres psql -c "CREATE ROLE ${DB_USER} LOGIN PASSWORD '${DB_PASSWORD}';"
fi
if ! sudo -u postgres psql -tAc "SELECT 1 FROM pg_database WHERE datname='${DB_NAME}'" | grep -q 1; then
    sudo -u postgres createdb -O "${DB_USER}" "${DB_NAME}"
fi
sudo -u postgres psql -c "ALTER DATABASE ${DB_NAME} OWNER TO ${DB_USER};" >/dev/null

echo "==> [5/9] Creating Python virtualenv and installing dependencies"
if [ ! -d "${VENV_DIR}" ]; then
    python3 -m venv "${VENV_DIR}"
fi
# shellcheck disable=SC1091
source "${VENV_DIR}/bin/activate"
pip install --upgrade pip -q
pip install -r "${REPO_ROOT}/requirements.txt"

echo "==> [6/9] Generating configuration.py if missing"
CONFIG_FILE="${REPO_ROOT}/netbox/netbox/configuration.py"
if [ ! -f "${CONFIG_FILE}" ]; then
    SECRET_KEY="$(python3 "${REPO_ROOT}/netbox/generate_secret_key.py")"
    PEPPER="$(python3 -c 'import secrets; print(secrets.token_urlsafe(50)[:50])')"
    cat > "${CONFIG_FILE}" <<EOF
# Auto-generated by .cursor/scripts/install.sh for local Cloud Agent development.
# This file is gitignored and must never be committed.
ALLOWED_HOSTS = ['*']

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': '${DB_NAME}',
        'USER': '${DB_USER}',
        'PASSWORD': '${DB_PASSWORD}',
        'HOST': 'localhost',
        'PORT': '',
        'CONN_MAX_AGE': 300,
    }
}

REDIS = {
    'tasks': {
        'HOST': 'localhost',
        'PORT': 6379,
        'USERNAME': '',
        'PASSWORD': '',
        'DATABASE': 0,
        'SSL': False,
    },
    'caching': {
        'HOST': 'localhost',
        'PORT': 6379,
        'USERNAME': '',
        'PASSWORD': '',
        'DATABASE': 1,
        'SSL': False,
    }
}

SECRET_KEY = '${SECRET_KEY}'

API_TOKEN_PEPPERS = {
    1: '${PEPPER}',
}

DEBUG = True

DEVELOPER = True
EOF
    echo "    Created ${CONFIG_FILE}"
else
    echo "    ${CONFIG_FILE} already exists; leaving it untouched"
fi

echo "==> [7/9] Building local documentation and collecting static files"
(cd "${REPO_ROOT}" && mkdocs build -q)
(cd "${REPO_ROOT}/netbox" && python3 manage.py collectstatic --no-input >/dev/null)

echo "==> [8/9] Applying database migrations"
(cd "${REPO_ROOT}/netbox" && python3 manage.py migrate)

echo "==> [9/9] Ensuring development superuser exists"
(cd "${REPO_ROOT}/netbox" && \
    DJANGO_SUPERUSER_PASSWORD="${DJANGO_SUPERUSER_PASSWORD}" \
    python3 manage.py createsuperuser --noinput \
        --username "${DJANGO_SUPERUSER_USERNAME}" \
        --email "${DJANGO_SUPERUSER_EMAIL}" 2>/dev/null \
    || echo "    Superuser '${DJANGO_SUPERUSER_USERNAME}' already exists")

echo "==> Install complete."
